services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mydotnetapi
    ports:
      - "5000:8080"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:17
    container_name: mydotnetdb
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
